#! /bin/csh

#----------------------------------------------------------------------#
#		TtestPlus Script
#		Auto-written by ScriptWriter
#----------------------------------------------------------------------#



#------------	
# adwarp regresions to parent dataset:
#

foreach subject ( gl052818 he042718 hw111117 is060118 jd051818 qh111717 rt022718 sw050818 tl111017 xl042618 yg042518 yq052218 )

	cd ../${subject}*
	adwarp -overwrite -apar anat+tlrc. -dpar zmid_reg_csfwm+orig. -dxyz 2.9 -prefix zmid_reg_csfwm

end


#------------	
# prepare files and variables for the ttest:
#

cd /Users/blevins/Desktop/cultsid/scripts
@ count = 1
mkdir -p /Users/blevins/Desktop/cultsid/ttest/mid_n12


#------------	
# set the stats variable to iterate alongside outfiles:
#

set stats = ( 19 22 25 28 31 34 )


#------------	
# perform the ttests:
#


#foreach outfile ( csf wm ant out gvnant lvnant hgvnout mgvnout lgvnout nvhlout nvmlout nvllout )
foreach outfile ( csf wm ant out gvnant lvnant )
	set stat = $stats[${count}]
	@ count = $count + 1
	

	3dttest++ -overwrite -prefix ./${outfile}z -toz -AminusB \
		-setA \
                "../gl052818/zmid_reg_csfwm+tlrc[${stat}]" \
                "../he042718/zmid_reg_csfwm+tlrc[${stat}]" \
                "../jd051818/zmid_reg_csfwm+tlrc[${stat}]" \
		"../rt022718/zmid_reg_csfwm+tlrc[${stat}]" \
                -setB \
		"../hw111117/zmid_reg_csfwm+tlrc[${stat}]" \
                "../is060118/zmid_reg_csfwm+tlrc[${stat}]" \
                "../qh111717/zmid_reg_csfwm+tlrc[${stat}]" \
                "../sw050818/zmid_reg_csfwm+tlrc[${stat}]" \
                "../tl111017/zmid_reg_csfwm+tlrc[${stat}]" \
                "../xl042618/zmid_reg_csfwm+tlrc[${stat}]" \
                "../yg042518/zmid_reg_csfwm+tlrc[${stat}]" \
                "../yq052218/zmid_reg_csfwm+tlrc[${stat}]" \
	
	mv ${outfile}z* /Users/blevins/Desktop/cultsid/ttest/mid_n12

end
