#! /bin/csh

#----------------------------------------------------------------------#
#		TtestPlus Script
#		Auto-written by ScriptWriter
#----------------------------------------------------------------------#

set script_dir = `pwd`  

#------------	
# adwarp regresions to parent dataset:
#

foreach subject ( rt022718 he042718 jd051818 gl052518 ac081918 kt082818 mp083018 lp102118 ch102218 nb102318 lh102418 jk102518 fd111018 sm110518 mp110618 sw110818 mc111218 dv111518 kl112918 jd072919 tl111017 hw111117 qh111717 yg042518 xl042618 sw050818 yq052218 is060118 yp070418 yl070418 yl070518 yw070618 xz071218 mh071418 yx072518 yl080118 yw081018 yd081018 js101518 al052019 jl053119 wx060119 yd072319 az072519 yy072919 pw073019 yl073119 )

	cd ../data/fmri/${subject}*
	adwarp -overwrite -apar anat+tlrc. -dpar zsid_reg_csfwm+orig. -dxyz 2.9 -prefix zsid_reg_csfwm
    cd $script_dir

end


#------------	
# prepare files and variables for the ttest:
#

@ count = 1
mkdir ../ttest/
mkdir ../ttest/sid


#------------	
# set the stats variable to iterate alongside outfiles:
#

# first six regressors (motion) have 3 each; start at 19
set stats = ( 19 22 25 28 31 34 37 40 )


#------------	
# perform the ttests:
#


#foreach outfile ( csf wm ant out gvnant lvnant hgvnout mgvnout lgvnout nvhlout nvmlout nvllout )
foreach outfile ( csf wm ant out gvnant lvnant gvnout lvnout )
    echo ${outfile}
	set stat = $stats[${count}]
	@ count = $count + 1
	

	3dttest++ -overwrite -prefix ./${outfile}z -toz -AminusB \
		-setA \
            "../data/fmri/rt022718/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/he042718/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/jd051818/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/gl052518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/ac081918/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/kt082818/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/mp083018/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/lp102118/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/ch102218/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/nb102318/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/lh102418/zsid_reg_csfwm+tlrc[${stat}]" \
            #"../data/fmri/jk102518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/fd111018/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/sm110518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/mp110618/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/sw110818/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/mc111218/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/dv111518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/kl112918/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/jd072919/zsid_reg_csfwm+tlrc[${stat}]" \
        -setB \
            #"../data/fmri/tl111017/zsid_reg_csfwm+tlrc[${stat}]" \
            #"../data/fmri/hw111117/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/qh111717/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yg042518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/xl042618/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/sw050818/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yq052218/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/is060118/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yp070418/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yl070418/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yl070518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yw070618/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/xz071218/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/mh071418/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yx072518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yl080118/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yw081018/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yd081018/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/js101518/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/al052019/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/jl053119/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/wx060119/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yd072319/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/az072519/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/yy072919/zsid_reg_csfwm+tlrc[${stat}]" \
            "../data/fmri/pw073019/zsid_reg_csfwm+tlrc[${stat}]" \
            #"../data/fmri/yl073119/zsid_reg_csfwm+tlrc[${stat}]" 

	mv ${outfile}z* ../ttest/sid

end
