#! /bin/csh
	
	####                                                                  ####
	########################## create csf and wm #############################
	####                                                                  ####
	
set anatfile = anat
set masks = ( wm_mask csf_mask )

# output file after preprocessing
set regfiles = ( sid_mbnf mid_mbnf )

set subjects = ( test )
				 
foreach subject ( ${subjects} )
	cd ../data/${subject}*  
	echo processing ${subject}
	
	foreach maskname ( ${masks} )
		if( -e ${maskname}r+orig.HEAD) then
			rm ${maskname}r+orig.*
		endif
	end
	
	foreach regfile (${regfiles})

		foreach mask ( ${masks} )

			3dfractionize -overwrite -template ${regfile}+orig -input ../../masks/${mask}+tlrc -warp ${anatfile}+tlrc -clip 0.1 -preserve -prefix ${regfile}_${mask}r+tlrc
			
			if ( -e l${mask}.tc ) then
				rm l${regfile}_${mask}.1D
		    endif
			if ( -e r${mask}.tc ) then
				rm r${regfile}_${mask}.1D
			endif
			if ( -e b${mask}.tc ) then
				rm b${regfile}_${mask}.1D
			endif

			3dmaskave -mask ${regfile}_${mask}r+orig -quiet -mrange 1 1 ${regfile}+orig > l${regfile}_${mask}.1D
			3dmaskave -mask ${regfile}_${mask}r+orig -quiet -mrange 2 2 ${regfile}+orig > r${regfile}_${mask}.1D
			3dmaskave -mask ${regfile}_${mask}r+orig -quiet -mrange 1 2 ${regfile}+orig > b${regfile}_${mask}.1D
		end
		
	end
	cd ../scripts
end
